name: Build Executables

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Linux Executable
      run: |
        pyinstaller --onefile --name oiva-linux oiva.py
        mkdir -p artifacts-linux
        cp dist/oiva-linux artifacts-linux/

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-executable
        path: artifacts-linux/

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [64, 32]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 重点修复：统一使用 Python 3.10
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        architecture: ${{ matrix.architecture == 32 && 'x86' || 'x64' }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Windows Executable
      run: |
        pyinstaller --onefile --name oiva-${{ matrix.architecture }}bit.exe --hidden-import tzdata oiva.py
        mkdir artifacts-windows
        copy dist\oiva-*.exe artifacts-windows\

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-${{ matrix.architecture }}bit
        path: artifacts-windows/

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
    - name: Download Linux artifacts
      uses: actions/download-artifact@v4
      with:
        name: linux-executable
        path: combined-artifacts

    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: windows-${{ matrix.architecture }}bit  # 需遍历架构，此处需调整
        path: combined-artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: combined-artifacts/*